repos:
  - repo: https://github.com/ambv/black
    rev: 23.12.1
    hooks:
      - id: black
        types: [python]
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          [flake8-docstrings, flake8-type-checking, flake8-bugbear, pep8-naming]
      - id: flake8
        stages: [manual]
        additional_dependencies: [darglint]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.910"
    hooks:
      - id: mypy
        name: mypy-ret
        files: ^ret/ret/.*\.py$
        entry: mypy ret
        pass_filenames: false
